version: '3.8'

services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 --timeout 300 app:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: blogs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
